### ISSUE TITLE
Crash when started crafting then closing crafting table gui and opening it again.

### ISSUE THREAD

**Issue by RDKRACZ** [jingshenSN2/CraftTime#1]
https://gist.github.com/RDKRACZ/7064cdc4cb25550947c05fbad9207d70

**Comment by RDKRACZ** [comment]
Albo another crash when I opened the crafting table with previously crafted iron boots.

```
java.lang.NullPointerException: Cannot invoke "sn2.timecraft.ITimeCraftPlayer.tick(net.minecraft.class_1799)" because "this.player" is null
	at Not Enough Crashes deobfuscated stack trace.(1.16.4+build.1)
	at net.minecraft.client.gui.screen.ingame.CraftingScreen.handler$bhn000$timecraft$tick(CraftingScreen:548)
	at net.minecraft.client.gui.screen.ingame.CraftingScreen.tick(CraftingScreen:54)
	at net.minecraft.client.MinecraftClient.method_1572(MinecraftClient:1526)
	at net.minecraft.class_310$$Lambda$7349/0x0000000086dc8960.run(Unknown Source)
	at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen:435)
	at net.minecraft.client.MinecraftClient.tick(MinecraftClient:1526)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1021)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:681)
	at net.minecraft.client.MinecraftClient.handler$cjj000$afterCrashHandled(MinecraftClient:12404)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:699)
	at net.minecraft.client.main.Main.main(Main:215)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:564)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:139)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:564)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Affected screen --
Details:
	Screen name: net.minecraft.class_479
Stacktrace:
	at net.minecraft.class_437.method_25412(class_437.java:438)
	at net.minecraft.class_310.method_1574(class_310.java:1526)
	at net.minecraft.class_310.method_1523(class_310.java:1021)
	at net.minecraft.class_310.method_1514(class_310.java:681)
	at net.minecraft.class_310.handler$cjj000$afterCrashHandled(class_310.java:12404)
	at net.minecraft.class_310.method_1514(class_310.java:699)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:139)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
-- Affected level --
Details:
	All players: 1 total; [class_746['_K0RR_'/8144, l='ClientLevel', x=60.14, y=134.00, z=129.74]]
	Chunk stats: SodiumChunkCache: 1680
	Level dimension: minecraft:overworld
	Level spawn location: World: (208,65,-128), Chunk: (at 0,4,0 in 13,-8; contains blocks 208,0,-128 to 223,255,-113), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 3575 game time, 3575 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Linux (amd64) version 5.4.70-amd64-desktop
	Java Version: 15.0.2, AdoptOpenJDK
	Java VM Version: Eclipse OpenJ9 VM (JRE 15 Linux amd64-64-Bit Compressed References 20210121_172 (JIT enabled, AOT enabled)
OpenJ9   - 345e1b09e
OMR      - 741e94ea8
JCL      - 863b523566 based on jdk-15.0.2+7), Eclipse OpenJ9
	Memory: 259894640 bytes (247 MB) / 3879731200 bytes (3700 MB) up to 3879731200 bytes (3700 MB)
```

**Comment by jingshenSN2** [comment]
try version 0.2.1?

**Comment by RDKRACZ** [comment]
0.2.1 is only for forge.

**Comment by jingshenSN2** [comment]
![image](https://user-images.githubusercontent.com/40377373/106382555-55103a00-63fb-11eb-8088-fd308c3b580f.png)
There is a Fabric version 0.2.1.
Curseforge only shows the latest file I upload, so I use beta version as forge and alpha version as fabric~

**Comment by RDKRACZ** [comment]
ah I see, I will try.

**Comment by RDKRACZ** [comment]
0.2.1 is working great but seems like it doesn't have an entry in the Modmenu.

**Comment by RDKRACZ** [comment]
> 0.2.1 is working great but seems like it doesn't have an entry in the Modmenu.

Sorry! Was typing crafttime without the space between mods.

**Comment by RDKRACZ** [comment]
Didn't want to open a new issue for this - CraftTime is missing issues tag in fabric.mod.json.

**Comment by jingshenSN2** [comment]
ok, I will add it in the next version.
